namespace MyCore.LexicalAnalysis
{
    public enum TokenType
    {
        BYTE_ORDER_MARK = 1,
        SINGLE_LINE_DOC_COMMENT = 2,
        DELIMITED_DOC_COMMENT = 3,

        SINGLE_LINE_COMMENT = 4,
        DELIMITED_COMMENT = 5,
        WHITESPACES = 6,
        SHARP = 7,
        IDENTIFIERS = 8,

        ADD = 9,
        ALIAS = 10,
        ARGLIST = 11,
        AS = 12,
        ASCENDING = 13,
        ASYNC = 14,
        AWAIT = 15,

        BASE = 16,
        BOOL = 17,
        BREAK = 18,
        BY = 19,
        BYTE = 20,
        CASE = 21,
        CATCH = 22,
        CHAR = 23,

        CHECKED = 24,
        CLASS = 25,
        CONST = 26,
        CONTINUE = 27,
        DECIMAL = 28,
        DEFAULT = 29,
        DELEGATE = 30,

        DESCENDING = 31,
        DO = 32,
        DOUBLE = 33,
        DYNAMIC = 34,
        ELSE = 35,
        ENUM = 36,
        EQUALS = 37,

        EVENT = 38,
        EXPLICIT = 39,
        EXTERN = 40,
        FALSE = 41,
        FINALLY = 42,
        FIXED = 43,
        FLOAT = 44,

        FOR = 45,
        FOREACH = 46,
        FROM = 47,
        GET = 48,
        GOTO = 49,
        GROUP = 50,
        IF = 51,
        IMPLICIT = 52,

        IN = 53,
        INT = 54,
        INTERFACE = 55,
        INTERNAL = 56,
        INTO = 57,
        IS = 58,
        JOIN = 59,
        LET = 60,

        LOCK = 61,
        LONG = 62,
        NAMEOF = 63,
        NAMESPACE = 64,
        NEW = 65,
        NULL = 66,
        OBJECT = 67,

        ON = 68,
        OPERATOR = 69,
        ORDERBY = 70,
        OUT = 71,
        OVERRIDE = 72,
        PARAMS = 73,
        PARTIAL = 74,

        PRIVATE = 75,
        PROTECTED = 76,
        PUBLIC = 77,
        READONLY = 78,
        REF = 79,
        REMOVE = 80,
        RETURN = 81,

        SBYTE = 82,
        SEALED = 83,
        SELECT = 84,
        SET = 85,
        SHORT = 86,
        SIZEOF = 87,
        STACKALLOC = 88,

        STATIC = 89,
        STRING = 90,
        STRUCT = 91,
        SWITCH = 92,
        THIS = 93,
        THROW = 94,
        TRUE = 95,

        TRY = 96,
        TYPEOF = 97,
        UINT = 98,
        ULONG = 99,
        UNCHECKED = 100,
        UNSAFE = 101,
        USHORT = 102,

        USING = 103,
        VAR = 104,
        VIRTUAL = 105,
        VOID = 106,
        VOLATILE = 107,
        WHEN = 108,
        WHERE = 109,

        WHILE = 110,
        YIELD = 111,
        IDENTIFIER = 112,
        LITERAL_ACCESS = 113,
        INTEGER_LITERAL = 114,

        HEX_INTEGER_LITERAL = 115,
        REAL_LITERAL = 116,
        CHARACTER_LITERAL = 117,
        REGULAR_STRING = 118,

        VERBATIUM_STRING = 119,
        INTERPOLATED_REGULAR_STRING_START = 120,
        INTERPOLATED_VERBATIUM_STRING_START = 121,

        OPEN_BRACE = 122,
        CLOSE_BRACE = 123,
        OPEN_BRACKET = 124,
        CLOSE_BRACKET = 125,

        OPEN_PARENS = 126,
        CLOSE_PARENS = 127,
        DOT = 128,
        COMMA = 129,
        COLON = 130,
        SEMICOLON = 131,

        PLUS = 132,
        MINUS = 133,
        STAR = 134,
        DIV = 135,
        PERCENT = 136,
        AMP = 137,
        BITWISE_OR = 138,

        CARET = 139,
        BANG = 140,
        TILDE = 141,
        ASSIGNMENT = 142,
        LT = 143,
        GT = 144,
        INTERR = 145,

        DOUBLE_COLON = 146,
        OP_COALESCING = 147,
        OP_INC = 148,
        OP_DEC = 149,
        OP_AND = 150,

        OP_OR = 151,
        OP_PTR = 152,
        OP_EQ = 153,
        OP_NE = 154,
        OP_LE = 155,
        OP_GE = 156,
        OP_ADD_ASSIGNMENT = 157,

        OP_SUB_ASSIGNMENT = 158,
        OP_MULT_ASSIGNMENT = 159,
        OP_DIV_ASSIGNMENT = 160,

        OP_MOD_ASSIGNMENT = 161,
        OP_AND_ASSIGNMENT = 162,
        OP_OR_ASSIGNMENT = 163,
        OP_XOR_ASSIGNMENT = 164,

        OP_LEFT_SHIFT = 165,
        OP_LEFT_SHIFT_ASSIGNMENT = 166,
        DOUBLE_CURLY_INSIDE = 167,

        OPEN_BRACE_INSIDE = 168,
        REGULAR_CHAR_INSIDE = 169,
        VERBATIUM_DOUBLE_QUOTE_INSIDE = 170,

        DOUBLE_QUOTE_INSIDE = 171,
        REGULAR_STRING_INSIDE = 172,
        VERBATIUM_INSIDE_STRING = 173,

        CLOSE_BRACE_INSIDE = 174,
        FORMAT_STRING = 175,
        DIRECTIVE_WHITESPACES = 176,

        DIGITS = 177,
        DEFINE = 178,
        UNDEF = 179,
        ELIF = 180,
        ENDIF = 181,
        LINE = 182,
        ERROR = 183,

        WARNING = 184,
        REGION = 185,
        ENDREGION = 186,
        PRAGMA = 187,
        DIRECTIVE_HIDDEN = 188,

        CONDITIONAL_SYMBOL = 189,
        DIRECTIVE_NEW_LINE = 190,
        TEXT = 191,
        DOUBLE_CURLY_CLOSE_INSIDE = 192,
        EOF = -1
    }
}